mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include ('polls.urls')), # any URL beginning polls/ will now use our polls/urls.py router
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
# here we declare the URLs for our polls website
from django.urls import path
from . import views # i.e. from current location

# we can create a namespace for our app 
app_name = 'polls' #(so we can say 'polls:detail' rather than just 'detail')
# declare the patterns we will respond to
urlpatterns = [
    path( '', views.IndexView.as_view(), name='index' ), # here we use generic views i.e. classes cast as views
    path( 'child/', views.ChildView.as_view(), name='child' ),
    path( '<int:pk>/', views.DetailView.as_view(), name='detail'),
    path( '<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path( '<int:question_id>/vote/', views.vote, name='vote' ), # NB vote is never actually visible
    # review 'weather'
    path('weather/', views.weather, name='weather'),
    path('<int:weather_id>/weather_form/', views.weather_form, name='weather_form')
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.
# declare our data models here
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date      = models.DateTimeField('data published')
    # we can override the __str__ (for pretty output)
    def __str__(self):
        return self.question_text
    # we can add utility functions for our classes
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question    = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes       = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

class Weather(models.Model):
    city = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    temperature = models.FloatField(default=22)
    wind_speed = models.FloatField(default=0)
    wind_direction = models.IntegerField(default=0)
    def __str__(self):
        report_str = "{}: {} {} {} {}".format(self.city, self.description, self.temperature, self.wind_speed, self.wind_direction)
        return report_str

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
# Create your views here.
from .models import Question # also need to import Choice
from .models import Weather
# we will need a reverse URL lookup
from django.urls import reverse
from django.views import generic

# we replace the function index, result and detail with Class-based views
# Class based views descend from generic Templates
class IndexView(generic.ListView): # we are going to list data members!
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list' # Django will manage all the data linking for us
    def get_queryset(self): # we override the built-in get_queryset method
        '''return the last three published questions'''
        return Question.objects.order_by('-pub_date')[:3]

# view for an inherited template (this replicates the 'index' page)
class ChildView(generic.ListView): 
    template_name = 'polls/child.html'
    context_object_name = 'latest_question_list' 
    def get_queryset(self):
        '''return all the questions'''
        return Question.objects.order_by('-pub_date')

class DetailView(generic.DetailView): # this is a detail page!
    model = Question
    template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def demo_form(request):
    return render(request, 'polls/demo_form.html' )

def weather(request):
    weather_list = Weather.objects.order_by('city') 
    context = {'weather_list': weather_list}
    return render(request, 'polls/weather.html', context)

def weather_form(request, weather_id):
    # is it GET or POST?
    if request.method =='POST':
        # the form has been submitted, so save the changes and then show the 'weather' view
        selected_weather = get_object_or_404(Weather, pk=request.POST['id'])
        selected_weather.country = request.POST['country']
        selected_weather.city = request.POST['city']
        selected_weather.description = request.POST['description']
        selected_weather.temperature = request.POST['temperature']
        selected_weather.wind_speed = request.POST['wind_speed']
        selected_weather.wind_direction = request.POST['wind_direction']
        selected_weather.save()
        weather_list = Weather.objects.order_by('city') 
        context = {'weather_list': weather_list}
        return render(request, 'polls/weather.html', context)
    else:
        # for form has NOT yet been submitted - just show the weather_form view
        weather = get_object_or_404(Weather, pk=weather_id)
        context = {'weather':weather}
        return render(request, 'polls/weather_form.html', context)

mysite/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %} 
    <link rel='stylesheet' href='{% static "polls/polls.css" %}' type='text/css' /> 
    <title>{% block title %}My site{% endblock %}</title>
</head>

<body>
    <nav id="navbar">
        {% block navbar %}
            <a href='https://djangoproject.com'>Django Docs</a> |
            <a href='https://djangogirls.orgs'>Django Tutorials</a> |
            <a href='https://www.w3schools.com/Css/'>CSS Tutorial</a>
        {% endblock %}
    </nav>

    <article id="content">
        {% block content %}{% endblock %}
    </article>
    <footer>
        &copy;2020 read our <span id='unique'>legal notice</span>
    </footer>
</body>
</html>

mysite/polls/templates/polls/child.html
{% extends "polls/base.html" %}

{% block title %}My child page{% endblock %}

{% block content %}
    <h2>Template Inheritance</h2>
    <p>This template inherits from 'base'</p>
    {% if latest_question_list %}
    <ul>
        <!-- here we iterate over the model data -->
        {% for question in latest_question_list %}
        <!-- we can use the 'a' tag to make hyperlinks -->
        <!-- NB we can use 'url' to derive the exact URL and avoid hard coding it -->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <h3>There are no questions yet</h3>
    {% endif  %}
{% endblock %}

mysite/polls/templates/polls/demo_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Example Form</title>
    {% load static %} 
    <link rel='stylesheet' href='{% static "polls/polls.css" %}' type='text/css' />

</head>
<body>
    <!-- sample HTML form with various field types -->
    <form action='' method='POST'>
        {%  csrf_token %}
        <input name='username' id='username' type="text" placeholder="enter your name" 
            value='Ada Lovelace'
            required/>
        <!-- br put a new line -->
        <br/>
        <input name='useremail' id='useremail' type="email" placeholder="enter your email" required/>
        <br/>
        <textarea name='info' id='info' placeholder="enter lots of info..."></textarea>
        <br/>
        <select name='lunch' id='lunch'>
            <option value='0'>Salad</option>
            <option value='1'>Soup</option>
            <option value='3'>Cake</option>
            <option selected value='4'>Fruit</option>
            <option value='5'>Other</option>
        </select>
        <br/>
        <button>Go</button>
    </form>
</body>
</html>

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- we can interpolate values - careful, Django works INSIDE comments -->
    <title>Details for Question {{question.id}}</title>
    {% load static %} 
    <link rel='stylesheet' href='{% static "polls/polls.css" %}' type='text/css' />
</head>
<body>
    <h2>Details for Question {{ question.id }}</h2>
    <p>{{ question.question_text }}</p>
    <nav>
        <a href='/polls/'>Home</a>
    </nav>
    <section>
        <!-- it's a good idea to have somewhere to show error messages -->
        {% if error_message %}
            <aside>
                <p><strong class='highlight'>{{ error_message}}</strong></p>
            </aside>
        {% endif %}

        <!-- we can declare a form for the user to place their vote -->
        <form action='{% url "polls:vote" question.id %}' method="POST">
            <!-- we must protect against cross-site request forgeries -->
            {% csrf_token %}
        <!-- iterate over the choices -->
            {% for choice in question.choice_set.all %}
                <input type="radio" name='choice' 
                    id='choice{{forloop.counter}}'
                    value='{{choice.id}}' /> {{ choice.choice_text }}
            {% endfor %}
        <!-- forms need some way to be sumbitted -->
        <input type='submit' value='Vote' />
        </form>
    </section>
</body>
</html>

mysite/polls/templates/polls/index.html
<!-- type ! then press tab to get a default web page -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to the Polls App Home Page</title>
    <!-- we can link to style sheets -->
    <!-- load static enables us to use static assets in this template -->
    {% load static %} 
    <link rel='stylesheet' href='{% static "polls/polls.css" %}' type='text/css' />
</head>

<body>
    <!-- we could use div, but better to use article etc. i.e. semantic tags -->
    <header>
        <h1 class='highlight'>Django Tutorial</h1>
    </header>
    <nav>
        <a href='https://djangoproject.com'>Django Docs</a> |
        <a href='https://djangogirls.orgs'>Django Tutorials</a> |
        <a href='https://www.w3schools.com/Css/'>CSS Tutorial</a> |
        <a href='weather/'>Review Exercise Solutions</a> |
        <a href='child/'>A Child View (using template inheritance)</a>
    </nav>
    <article>
        <!-- our Django template content goes here (using interpolation)  -->
        {% if latest_question_list %}
        <ul>
            <!-- here we iterate over the model data -->
            {% for question in latest_question_list %}
            <!-- we can use the 'a' tag to make hyperlinks -->
            <!-- NB we can use 'url' to derive the exact URL and avoid hard coding it -->
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <h3>There are no questions yet</h3>
        {% endif  %}
    </article>
    <aside>
        <button id='btnCookies'>Agree to cookies</button>
        <br/>
        <img id='my_image' src='http://placekitten.com/240/120' />
        <br/>
        w: <input type='range' min='12' max='640' step='10' id='width' />
        <br/>
        h: <input type='range' min='12' max='640' step='10' id='height' />
    </aside>
    <footer>
        &copy;2020 read our <span id='unique'>legal notice</span>
    </footer>
</body>
<!-- we can declare a script -->
<script>
// JavaScript is the ONLY client-side code we EVER write
// code to control the image
let my_image = document.getElementById('my_image')
let width = document.getElementById('width')
let height = document.getElementById('height')

const adjustImage = ()=>{ // similar to old-skool function adjustImage(){}
    new_w = width.value
    new_h = height.value
    new_src = `http://placekitten.com/${new_w}/${new_h}` // string interpolation
    // console.log(new_src)
    my_image.setAttribute('src', new_src)
} 
width.addEventListener('change', adjustImage)
height.addEventListener('change', adjustImage)


// we can access any data from Django
// but ONLY at the point it is injected into the page
// i.e. at page creation
// (there is no Python or Django running in a browser!)
let latest_list = "{{latest_question_list}}" // quotes since it is serialized
console.log(latest_list)


// declare functions
const handleClick = ()=>{ // modern JavaScript functions use 'arrow' syntax
    event.target.removeEventListener('click', handleClick) // first remove any event listeners
    event.target.setAttribute('style', 'display:none')
}

// we can handle cookie permission
btn = document.getElementById('btnCookies')
btn.addEventListener('click', handleClick)

// we can 'poll' or 'heartbeat' to auto-submit fresh data points
// use setInterval
const newData = ()=>{ // 'latest' is accesing the Django data injected into the page
    console.log( new Date() ) // Date() is a timestamp
}
//          function TO CALL, not the actual call
// setInterval(newData, 1000) // 1000 milliseconds

</script>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
    {% load static %} 
    <link rel='stylesheet' href='{% static "polls/polls.css" %}' type='text/css' />

</head>
<body>
    <h2>Results for: {{ question.question_text }}</h2>
    <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} votes: {{ choice.votes }}</li>
        {% endfor %}
    </ul>

    <a href='{% url "polls:detail" question.id %}'>Vote again</a>
</body>
</html>

mysite/polls/templates/polls/weather.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather Reports</title>
    {% load static %}
    <link rel='stylesheet' href='{% static "polls/polls.css" %}' type='text/css' />

</head>

<body>
    <h2>Weather Reports</h2>
    {% if weather_list %}
    <ul>
        {% for weather in weather_list %}
        <li><a href="{% url 'polls:weather_form' weather.id %}">
                <span class='city'>City: {{ weather.city }} </span>
                <span class='country'>({{weather.country}}) </span>
                <span class='temp'>Temperature: {{weather.temperature}}&deg;</span>
                <span class='speed'>Wind Speed: {{weather.wind_speed}}</span>
                <span class='dir'>Wind Direction: {{weather.wind_direction}}&deg;</span>
            </a></li>
        {% endfor %}
    </ul>
    {% else %}
    <h3 class='highlight'>There are no weather reports yet</h3>
    {% endif  %}
    <section>
        <!-- leave out the form tag, so there is no way it will accidentally submit to the server -->
        Category:
        <select id='cat'>
            <option>posts</option>
            <option>users</option>
            <option>albums</option>
            <option>photos</option>
            <option>todos</option>
        </select>
        <br />
        ID Number:
        <input type="number" min="1" max="9" step="1" id='num' value='1' />
        <br />
        <button id='btnGo'>Go</button>
        <hr />
        <!-- show any retrieved data -->
        <aside id='monitor'></aside>
        <hr />
    </section>
</body>
<script>
    // a function to get API end-point data
    const getData = () => {
        // retrieve the user values
        document.getElementById('cat')
        document.getElementById('num')
        let chosen_cat = cat.value
        let chosen_num = num.value

        // we can access end-point data via REST APIs
        // the modern way is to use the FETCH API
        // try posts/n or albums/n etc. (users, totos)
        fetch(`http://jsonplaceholder.typicode.com/${chosen_cat}/${chosen_num}`) // an asynchronous request
            .then((response) => { return response.json() }) // make sure it's json
            .then((data) => {
                // console.log(data)
                monitor = document.getElementById('monitor') // for ALL browsers
                monitor.innerHTML = JSON.stringify(data)
                // monitor.innerHTML = data.title
            })
    }

    // add a listener to the button
    let btnGo = document.getElementById('btnGo')
    btnGo.addEventListener('click', getData) // NOT the call yet


</script>

</html>

mysite/polls/templates/polls/weather_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Weather Form</title>
    {% load static %}
    <link rel='stylesheet' href='{% static "polls/polls.css" %}' type='text/css' />

</head>

<body>
    <section>
        <h3>Weather Form for {{weather_id}}</h3>
        {% if error_message %}
        <aside>
            <p><strong>{{ error_message}}</strong></p>
        </aside>
        {% endif %}
        <form action='{% url "polls:weather_form" weather.id %}' method="POST">
            {% csrf_token %}
            Country:
            <select name='country' id='country'>
                <option selected value='{{weather.country}}'>{{weather.country}}</option>
                <option value='uk'>United Kingdom</option>
                <option value='ie'>Ireland</option>
                <option value='aus'>Australia</option>
                <option value='usa'>USA</option>
            </select>
            <br />
            City:
            <input type="text" placeholder="enter city name" required id='city' name='city' value="{{weather.city}}" />
            <br />
            Description:
            <textarea id='description' name='description'>{{weather.description}}</textarea>
            <br />
            Temperature:
            <input type="text" size='6' value='{{weather.temperature}}' name='temperature' id='temperature' />
            &deg; Celcius
            <br/>
            Wind Speed: 
            <input type="text" id='wind_speed' name='wind_speed' placeholder="wind speed"/>
            Wind Direction: 
            <input type="number" id='wind_direction' name='wind_direction' 
                min="0" max="360" placeholder="wind direction" />
            <!-- a hidden field to make sure we pass the ID for this weather report -->
            <input type='hidden' value='{{weather.id}}' id='id' name='id' />
            <br/>
            <input type='submit' value='save changes' />
        </form>
        <hr />
        <section>
            <button id='btnWeather'>Get Weather</button>
        </section>
        <hr />

    </section>
</body>
<script>
    let weatherStub = 'http://api.openweathermap.org/data/2.5/weather?q='
    let weatherAPPID = '&APPID=48f2d5e18b0d2bc50519b58cce6409f1'
    let units = '&units=metric'
    let btnWeather = document.getElementById('btnWeather')

    const getWeather = () => {
        let chosen_city = document.getElementById('city').value
        let chosen_country = document.getElementById('country').value
        let temperature = document.getElementById('temperature')
        let description = document.getElementById('description')
        let speed = document.getElementById('wind_speed')
        let direction = document.getElementById('wind_direction')
        let weatherURL = `${weatherStub}${chosen_city},${chosen_country}${weatherAPPID}${units}`
        console.log(weatherURL)
        // make API call
        fetch(weatherURL)
            .then((request) => { return request.json() })
            .then((data) => {
                console.log(data)
                // put the retrieved valus into the form
                temperature.value = data.main.temp
                description.value = data.weather[0]['description']
                speed.value = data.wind['speed']
                direction.value = data.wind['deg']
            })
    }
    btnWeather.addEventListener('click', getWeather)

</script>

</html>